USE codeup_test_db;
SELECT "1. Broadcast's albums include:" AS "";
SELECT name AS "", release_date AS "" FROM albums WHERE artist = "Broadcast" ORDER BY release_date;
SELECT "2. The Modern Lovers' self-title album was released in:" AS "";
SELECT release_date AS "" FROM albums WHERE name = "The Modern Lovers";
SELECT "3. The genre of Life's A Riot With Spy vs. Spy by Billy Bragg is:" AS "";
SELECT genre AS "" FROM albums WHERE artist = "Billy Bragg";
SELECT "4. The following albums were released in the 90s:" AS "";
SELECT name AS "", release_date AS "" FROM albums WHERE release_date BETWEEN 1990 AND 1999 ORDER BY release_date ;
SELECT "5. The following albums sold more than 2 million copies" AS "";
SELECT name AS "" FROM albums WHERE sales_in_millions >= 2;
SELECT "6. Here are some punkish albums:" AS "";
SELECT name AS "", artist AS "" FROM albums WHERE genre like "%punk%";